[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "clear"

[[session]]
name = "poseidon"
path = "~/Documents/repos/work/poseidon"
startup_command = "tmux split-window -v -p 80"

[[session]]
name = "scrooge"
path = "~/Documents/repos/work/scrooge"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "go-service"
path = "~/Documents/repos/work/go-service"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "go-common"
path = "~/Documents/repos/work/go-common"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "go-authorize"
path = "~/Documents/repos/work/go-authorize"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "go-frontegg"
path = "~/Documents/repos/work/go-frontegg"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "zig-exercises"
path = "~/Documents/repos/personal/ziglings.org"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "fc-infra-kubernetes"
path = "~/Documents/repos/work/fc-infra-kubernetes"
startup_command = "clear"
