require("mleonidas/packer")
require("mleonidas/lsp_cmp")
require("mleonidas/lsp")
require("mleonidas/statusline")
require("mleonidas/octo")
require("mleonidas/treesitter")
require("mleonidas/rest")
require("mleonidas/go")
require("mleonidas/debugger")
require("mleonidas/vgit")
require("mleonidas/todo_comments")
require("mleonidas/neogit")

